Repository Taaveez/Taaveez-android, pull requests merged in 2023-06, with the labels that each got.

#65 Fix : Updated Versions of dependencies
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/misc.xml
  app/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle
Labels: level1

#75 Additions in issue template done
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/styles.yml
Labels: gssoc23, level1

#91 website link added
  app/src/main/java/com/itssuryansh/taaveez/About.kt
Labels: gssoc23, level3
